language: node_js
node_js:
- 8.9.0
sudo: false
cache:
  apt: true
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - npm install -g hexo-cli
install:
- npm install -g hexo --no-optional
- npm install
- npm install hexo --no-optional
script:
- hexo clean
- hexo generate
after_script:
  - cd ./public
  - git init
  - git config --global user.name 'koyasite'
  - git config --global user.email 'me@virgo.one'
  - git config --global user.name 'virgoone'
  - git config --global user.email 'w2008second@163.com'
  - git add .
  - git commit -m "TravisCI 自动部署"
   # Github Pages
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://koyasite:${CODING_TOKEN}@${CO_REF}" master:master

env:
 global:
   # Github Pages
   - GH_REF: github.com/virgoone/virgoone.github.io
   # Coding Pages
   - CO_REF: e.coding.net/moss/koyasite/koyasite.git
